name: Render

on: push

jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker://pandoc/latex:3.1
        with:
          args: --output=render.pdf main.md
          
      - uses: actions/upload-artifact@v3
        with:
          name: render.pdf
          path: render.pdf